[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer_runs = 1_000_000
solc = '0.8.17'
remappings = [
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts',
    'openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts',
]



# See more config options https://github.com/foundry-rs/foundry/tree/master/config